config/routes.rb
Rails.application.routes.draw do
  get 'equipments/create'

  # devise_scope :user do
  #   get '/sign_in', to: 'devise/sessions#new'
  #   get '/sign_up', to: 'devise/registrations#new', as: 'new_user_registration'
  # end

  devise_for :users, :store_managers, :lab_owners, :super_users
  root 'static_pages#home'

  resources :users, only: [:show]
  resources :store_managers, only: [:show]
  resources :lab_owners, only: [:show, :index]
  resources :super_users, only: [:show]

  resources :equipment, only: [:create, :index, :update, :show, :edit]
  
  resources :move_requests, only: [:create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :lab_owner
  has_many :location_histories

  def update_location_history
    
    last_history = location_histories.order(created_at: :desc).first
    if !request? && !in_transit? && (last_history.nil? || (lab_owner.lab != last_history.location))
      location_histories.create(location: lab_owner.lab)
    end
  end
end

app/models/lab_owner.rb
class LabOwner < User
  has_many :equipment
  has_many :send_requests, class_name: "MoveRequest",
                          foreign_key: "from_id",
                          dependent: :destroy
  has_many :receive_requests, class_name: "MoveRequest",
                            foreign_key: "to_id",
                            dependent: :destroy
end

app/models/location_history.rb
class LocationHistory < ApplicationRecord
  belongs_to :equipment
end

app/models/move_request.rb
class MoveRequest < ApplicationRecord
  belongs_to :equipment
  belongs_to :from, class_name: "LabOwner"
  belongs_to :to, class_name: "LabOwner"

  def move_equipment
    if to_approved == 'Approved' && hod_approved == 'Approved'
      equipment.update_attributes(lab_owner_id: to_id, in_transit: false)
      equipment.save
    elsif to_approved == 'Rejected' || hod_approved == 'Rejected'
      equipment.update_attributes(in_transit: false)
      equipment.save
    end
  end
end

app/models/store_manager.rb
class StoreManager < User
end

app/models/super_user.rb
class SuperUser < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:lab, :email, :password, :password_confirmation)}
  end

  def after_sign_in_path_for(resource)
    # user_path(resource)
    if resource.type == 'StoreManager'
      store_manager_path(resource)
    elsif resource.type == 'LabOwner'
      lab_owner_path(resource)
    elsif resource.type == 'SuperUser'
      super_user_path(resource)
    else
      user_path(resource)
    end
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :authenticate_user!

  def create
    @equipment = Equipment.create(equipment_params)
    if @equipment.save
      flash[:success] = "Equipment added successfully"
      @equipment.update_location_history
      redirect_to user_dashboard
    else
      flash[:danger] = "Equipment could not be added"
      redirect_to user_dashboard
    end
  end

  def update
    @equipment = Equipment.find(params[:id])
    @equipment.update_attributes(equipment_params)
    @equipment.save
    @equipment.update_location_history
    if !@equipment.request?
      redirect_to equipment_path(@equipment)
    else
      redirect_to user_dashboard
    end
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def show
    @equipment = Equipment.find(params[:id])
    @location_histories = @equipment.location_histories.order(created_at: :desc)
  end


  def index
    if (current_user.type == 'LabOwner')
      @equipment = current_user.equipment.where(request: false)
      @move_request = MoveRequest.new
    else
      @equipment = Equipment.where(request: false)
    end
  end

  private
    def equipment_params
      params.require(:equipment).permit(:model, :kind, :request, :approved, :location,
      :lab_owner_id, :status, :warranty_status)
    end

    def user_dashboard
      if current_user.nil?
        root_path
      elsif current_user.type == 'StoreManager'
        store_manager_path(current_user)
      elsif current_user.type == 'LabOwner'
        lab_owner_path(current_user)
      elsif current_user.type == 'SuperUser'
        super_user_path(current_user)
      end
    end
end

app/controllers/lab_owners_controller.rb
class LabOwnersController < ApplicationController
  before_action :authenticate_user!

  def show
    @lab_owner = LabOwner.find(params[:id])
    @equipment = Equipment.new
    @requests = current_user.equipment.where(request: true)
    @send_requests = current_user.send_requests
    @receive_requests = current_user.receive_requests
  end

  def index
    @lab_owners = LabOwner.all
  end
end

app/controllers/move_requests_controller.rb
class MoveRequestsController < ApplicationController
  before_action :authenticate_user!

  def create
    @move_request = current_user.send_requests.build(move_request_params)
    @equipment = @move_request.equipment
    @equipment.update_attributes(in_transit: true)
    if @move_request.save
      @equipment.save
      flash[:success] = "Move request created successfully!"
      redirect_to user_dashboard
    else
      flash[:danger] = "Move request could not be added!"
      redirect_to user_dashboard
    end
  end

  def update
    @move_request = MoveRequest.find(params[:id])
    @move_request.update_attributes(move_request_params)
    @move_request.save
    @move_request.move_equipment
    @move_request.equipment.update_location_history
    redirect_to user_dashboard
  end


  private
    def move_request_params
      params.require(:move_request).permit(:to_id, :equipment_id, :hod_approved, :to_approved)
    end

    def user_dashboard
      if current_user.nil?
        root_path
      elsif current_user.type == 'StoreManager'
        store_manager_path(current_user)
      elsif current_user.type == 'LabOwner'
        lab_owner_path(current_user)
      elsif current_user.type == 'SuperUser'
        super_user_path(current_user)
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/store_managers_controller.rb
class StoreManagersController < ApplicationController
  before_action :authenticate_user!

  def show
    @store_manager = StoreManager.find(params[:id])
    @equipment = Equipment.new
    @requests = Equipment.where(request: true)
  end
end

app/controllers/super_users_controller.rb
class SuperUsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @store_manager = SuperUser.find(params[:id])
    @requests = Equipment.where(request: true)
    @move_requests = MoveRequest.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(name="")
    base_title = "Equipment Tracker"
    if name.blank?
      title = base_title   
    else
      title = "#{name} | #{base_title}"
    end
  end

  def is_super_user?
    user_signed_in? && current_user.type == 'SuperUser'
  end

  def is_store_manager?
    user_signed_in? && current_user.type == 'StoreManager'
  end

  def is_lab_owner?
    user_signed_in? && current_user.type == 'LabOwner'
  end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/move_requests_helper.rb
module MoveRequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/equipment/_equipment.html.erb
<tr class="display-request-info">
  <th scope="row" class="display_barcode">
    <% if equipment.request %>
      <%= equipment.id %>
    <% else %>
      <%= link_to equipment.id, equipment_path(equipment.id) %>
    <% end %>
  </th>
  <td><%= equipment.model %></td>
  <td><%= equipment.kind %></td>
  <% if equipment.request %>
    <% unless is_lab_owner? %>
      <td><%= equipment.lab_owner.id %></td>
    <% end %>
    <% if equipment.approved == 'Approved' %>
      <td>
        <span class="label label-success">Approved</span>
        <% if is_store_manager? %>
          <%= simple_form_for equipment do |f| %>
            <%= f.input :request, as: :hidden, input_html: { value: false } %>
            <%= f.button :submit, 'Add', class: 'btn btn-xs' %>
          <% end %>
        <% end %>
      </td>
    <% elsif equipment.approved == 'Pending' %>
      <td>
        <span class="label label-warning">Pending</span>
        <% if is_super_user? %>
          <%= simple_form_for equipment do |f| %>
            <%= f.input :approved, as: :hidden, input_html: { value: 'Approved' } %>
            <%= f.button :submit, 'Approve', class: 'btn btn-xs' %>
          <% end %>
          <%= simple_form_for equipment do |f| %>
            <%= f.input :approved, as: :hidden, input_html: { value: 'Rejected' } %>
            <%= f.button :submit, 'Reject', class: 'btn btn-xs' %>
          <% end %>
        <% end %>
      </td>
    <% else %>
      <td>
        <span class="label label-danger">Rejected</span>
      </td>
    <% end %>
  <% else %>
    <td><%= equipment.lab_owner.lab %></td>
    <% if equipment.status == 'OK' %>
      <td><span class="label label-success">OK</span></td>
    <% else %>
      <td><span class="label label-danger">Not OK</span></td>
    <% end %>
    <% if equipment.warranty_status == 'OK' %>
      <td><span class="label label-success">In Warranty</span></td>
    <% else %>
      <td><span class="label label-warning">Not in warranty</span></td>
    <% end %>
    <% if is_lab_owner? %>
      <td>
        <%= simple_form_for @move_request do |f|%>
          <%= f.input :to_id, disabled: equipment.in_transit, input_html: { class: 'input-sm' }%>
          <%= f.input :equipment_id, as: :hidden, input_html: { value: equipment.id } %>
          <%= f.button :submit, 'Submit', class: 'btn btn-xs', disabled: equipment.in_transit %>
        <% end %>
      </td>
    <% end %>
  <% end %>
  <!--td>Move equipment</td-->
</tr>

app/views/equipment/edit.html.erb
<h1>View Equipment</h1>
<div class="row">
    <div class="col-md-3">
        <p id="equipment_id" hidden=true><%= @equipment.id %></p>
        <!-- Insert Barcode Here -->
        <img id="show_barcode" role="img" alt="The barcode"></img>
    </div>
    <div class="col-md-6">
        <%= simple_form_for @equipment do |f| %>
            <%= f.input :warranty_status, collection: [ "OK", "Not OK"] %>
             <%= f.input :status, collection: [ "OK", "Not OK" ] %>
            <%= f.button :submit %>
        <% end %>
    </div>
</div>

app/views/equipment/index.html.erb
<h1>All equipment</h1>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <table class="table table-hover" id="equipment-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Model</th>
                    <th>Type</th>
                    <th>Location</th>
                    <th>Status</th>
                    <th>Warranty Status</th>
                    <% if is_lab_owner? %>
                        <th>New Lab Owner ID (Move request)</th>
                    <% end %>
                </tr>
            </thead>
            <tbody>
                <%= render @equipment || "No equipment found" %>
            </tbody>
        </table>
    </div>
</div>

app/views/equipment/show.html.erb
<h1>View Equipment</h1>
<div class="row">
    <div class="col-md-3">
        <p id="equipment_id" hidden=true><%= @equipment.id %></p>
        <!-- Insert Barcode Here -->
        <img id="show_barcode" role="img" alt="The barcode"></img>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Model</h3></div>
            <div class="panel-body">
                <%= @equipment.model %>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Type</h3></div>
            <div class="panel-body">
                <%= @equipment.kind %>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Location</h3></div>
            <div class="panel-body">
                <%= @equipment.lab_owner.lab %>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title">Status</h3></div>
                    <div class="panel-body">
                        <% if @equipment.status == 'OK' %>
                            <span class="label label-success">OK</span>
                        <% else %>
                            <span class="label label-danger">Not OK</span>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title">Warranty Status</h3></div>
                    <div class="panel-body">
                        <% if @equipment.warranty_status == 'OK' %>
                            <span class="label label-success">In Warranty</span>
                        <% else %>
                            <span class="label label-warning">Not in warranty</span>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <%= link_to "Update", edit_equipment_path(@equipment) %>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Location History</h3></div>
            <div class="panel-body">
                <ul class="list-group">
                    <%= render @location_histories %>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/lab_owners/_lab_owner.html.erb
<tr class="display-request-info">
  <th scope="row">
      <%= lab_owner.id %>
  </th>
  <td><%= lab_owner.email %></td>
  <td><%= lab_owner.lab %></td>
</tr>

app/views/lab_owners/index.html.erb
<h1>All lab owners</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <table class="table table-hover" id="lab-owner-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Email ID</th>
                    <th>Lab</th>
                </tr>
            </thead>
            <tbody>
                <%= render @lab_owners || "No equipment found" %>
            </tbody>
        </table>
    </div>
</div>

app/views/lab_owners/show.html.erb
<h1>Dashboard</h1>
<div class="row">
    <div class="col-md-3">
      <%= simple_form_for @equipment do |f| %>
        <%= f.input :model %>
        <%= f.input :kind %>
        <%= f.input :request, as: :hidden, input_html: { value: 'true' } %>
        <%= f.input :lab_owner_id, as: :hidden, input_html: { value: current_user.id } %>
        <%= f.button :submit, 'Add new request' %>
      <% end %>
    </div>
    <div class="col-md-6">
        <h2>New Equipment requests</h2>
        <table class="table table-hover" id="equipment-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Model</th>
                    <th>Type</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <%= render @requests %>
            </tbody>
        </table>
    </div>
</div>
<br />
<hr>

<div class="row">
    <div class="col-md-6">
        <h2>Receive requests</h2>
        <table class="table table-hover" id="move-requests-table">
            <thead>
                <tr>
                    <th>Equipment #</th>
                    <th>From Lab Owner</th>
                    <th>To Lab Owner</th>
                    <th>HOD Approval Status</th>
                    <th>Receiver Lab Owner Approval Status</th>
                </tr>
            </thead>
            <tbody>
                <%= render @receive_requests %>
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <table class="table table-hover" id="move-requests-table">
            <h2>Send requests</h2>
            <thead>
                <tr>
                    <th>Equipment #</th>
                    <th>From Lab Owner</th>
                    <th>To Lab Owner</th>
                    <th>HOD Approval Status</th>
                    <th>Receiver Lab Owner Approval Status</th>
                </tr>
            </thead>
            <tbody>
                <%= render @send_requests %>
            </tbody>
        </table>
    </div>
</div>

app/views/location_histories/_location_history.html.erb
<li class="list-group-item">
    <%= location_history.location %>, <%= location_history.created_at.strftime('%F') %>
</li>

app/views/move_requests/_move_request.html.erb
<tr class="display-request-info">
  <th scope="row">
      <%= link_to move_request.equipment.id, equipment_path(move_request.equipment.id) %>
  </th>
  <td><%= move_request.from_id %></td>
  <td><%= move_request.to_id %></td>
  <% if move_request.hod_approved == 'Approved' %>
      <td>
        <span class="label label-success">Approved</span>
      </td>
    <% elsif move_request.hod_approved == 'Pending' %>
      <td>
        <span class="label label-warning">Pending</span>
        <% if is_super_user? %>
          <%= simple_form_for move_request do |f| %>
            <%= f.input :hod_approved, as: :hidden, input_html: { value: 'Approved' } %>
            <%= f.button :submit, 'Approve', class: 'btn btn-xs' %>
          <% end %>
          <%= simple_form_for move_request do |f| %>
            <%= f.input :hod_approved, as: :hidden, input_html: { value: 'Rejected' } %>
            <%= f.button :submit, 'Reject', class: 'btn btn-xs' %>
          <% end %>
        <% end %>
      </td>
    <% else %>
      <td>
        <span class="label label-danger">Rejected</span>
      </td>
    <% end %>

    <% if move_request.to_approved == 'Approved' %>
      <td>
        <span class="label label-success">Approved</span>
      </td>
    <% elsif move_request.to_approved == 'Pending' %>
      <td>
        <span class="label label-warning">Pending</span>
        <% if is_lab_owner? && current_user.id == move_request.to_id%>
          <%= simple_form_for move_request do |f| %>
            <%= f.input :to_approved, as: :hidden, input_html: { value: 'Approved' } %>
            <%= f.button :submit, 'Approve', class: 'btn btn-xs' %>
          <% end %>
          <%= simple_form_for move_request do |f| %>
            <%= f.input :to_approved, as: :hidden, input_html: { value: 'Rejected' } %>
            <%= f.button :submit, 'Reject', class: 'btn btn-xs' %>
          <% end %>
        <% end %>
      </td>
    <% else %>
      <td>
        <span class="label label-danger">Rejected</span>
      </td>
    <% end %>
</tr>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Equipment Tracker</h1>
    <h2>
        This is the homepage for the equipment tracker.
    </h2>
</div>

app/views/store_managers/show.html.erb
<h1>All requests</h1>
<div class="row">
    <!--div class="col-md-3">
      <%= simple_form_for @equipment do |f| %>
        <%= f.input :model %>
        <%= f.input :kind %>
        <%= f.input :lab_owner_id %>
        <%= f.button :submit, 'Add new equipment' %>
      <% end %>
    </div-->
    <div class="col-md-8 col-md-offset-2">
        <table class="table table-hover" id="equipment-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Model</th>
                    <th>Type</th>
                    <th>Lab Owner ID</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <%= render @requests %>
            </tbody>
        </table>
    </div>
</div>

app/views/super_users/show.html.erb
<h2>New equipment requests</h2>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <table class="table table-hover" id="equipment-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Model</th>
                    <th>Type</th>
                    <th>Lab Owner ID</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <%= render @requests %>
            </tbody>
        </table>
    </div>
</div>

<hr>

<h2>Move requests</h2>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <table class="table table-hover" id="move-requests-table">
            <thead>
                <tr>
                    <th>Equipment #</th>
                    <th>From Lab Owner</th>
                    <th>To Lab Owner</th>
                    <th>HOD Approval Status</th>
                    <th>Receiver Lab Owner Approval Status</th>
                </tr>
            </thead>
            <tbody>
                <%= render @move_requests %>
            </tbody>
        </table>
    </div>
</div>

app/views/users/show.html.erb
This will be the user page for the logged-in user