config/routes.rb
Rails.application.routes.draw do
  get 'equipments/create'

  # devise_scope :user do
  #   get '/sign_in', to: 'devise/sessions#new'
  #   get '/sign_up', to: 'devise/registrations#new', as: 'new_user_registration'
  # end

  devise_for :users, :store_managers, :lab_owners, :super_users
  root 'static_pages#home'

  resources :users, only: [:show]
  resources :store_managers, only: [:show]
  resources :lab_owners, only: [:show, :index]
  resources :super_users, only: [:show]

  resources :equipment, only: [:create, :index, :update, :show, :edit]
  
  resources :move_requests, only: [:create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :lab_owner
  has_many :location_histories

  def update_location_history
    
    last_history = location_histories.order(created_at: :desc).first
    if !request? && !in_transit? && (last_history.nil? || (lab_owner.lab != last_history.location))
      location_histories.create(location: lab_owner.lab)
    end
  end
end

app/models/lab_owner.rb
class LabOwner < User
  has_many :equipment
  has_many :send_requests, class_name: "MoveRequest",
                          foreign_key: "from_id",
                          dependent: :destroy
  has_many :receive_requests, class_name: "MoveRequest",
                            foreign_key: "to_id",
                            dependent: :destroy
end

app/models/location_history.rb
class LocationHistory < ApplicationRecord
  belongs_to :equipment
end

app/models/move_request.rb
class MoveRequest < ApplicationRecord
  belongs_to :equipment
  belongs_to :from, class_name: "LabOwner"
  belongs_to :to, class_name: "LabOwner"

  def move_equipment
    if to_approved == 'Approved' && hod_approved == 'Approved'
      equipment.update_attributes(lab_owner_id: to_id, in_transit: false)
      equipment.save
    elsif to_approved == 'Rejected' || hod_approved == 'Rejected'
      equipment.update_attributes(in_transit: false)
      equipment.save
    end
  end
end

app/models/store_manager.rb
class StoreManager < User
end

app/models/super_user.rb
class SuperUser < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:lab, :email, :password, :password_confirmation)}
  end

  def after_sign_in_path_for(resource)
    # user_path(resource)
    if resource.type == 'StoreManager'
      store_manager_path(resource)
    elsif resource.type == 'LabOwner'
      lab_owner_path(resource)
    elsif resource.type == 'SuperUser'
      super_user_path(resource)
    else
      user_path(resource)
    end
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :authenticate_user!

  def create
    @equipment = Equipment.create(equipment_params)
    if @equipment.save
      flash[:success] = "Equipment added successfully"
      @equipment.update_location_history
      redirect_to user_dashboard
    else
      flash[:danger] = "Equipment could not be added"
      redirect_to user_dashboard
    end
  end

  def update
    @equipment = Equipment.find(params[:id])
    @equipment.update_attributes(equipment_params)
    @equipment.save
    @equipment.update_location_history
    if !@equipment.request?
      redirect_to equipment_path(@equipment)
    else
      redirect_to user_dashboard
    end
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def show
    @equipment = Equipment.find(params[:id])
    @location_histories = @equipment.location_histories.order(created_at: :desc)
  end


  def index
    if (current_user.type == 'LabOwner')
      @equipment = current_user.equipment.where(request: false)
      @move_request = MoveRequest.new
    else
      @equipment = Equipment.where(request: false)
    end
  end

  private
    def equipment_params
      params.require(:equipment).permit(:model, :kind, :request, :approved, :location,
      :lab_owner_id, :status, :warranty_status)
    end

    def user_dashboard
      if current_user.nil?
        root_path
      elsif current_user.type == 'StoreManager'
        store_manager_path(current_user)
      elsif current_user.type == 'LabOwner'
        lab_owner_path(current_user)
      elsif current_user.type == 'SuperUser'
        super_user_path(current_user)
      end
    end
end

app/controllers/lab_owners_controller.rb
class LabOwnersController < ApplicationController
  before_action :authenticate_user!

  def show
    @lab_owner = LabOwner.find(params[:id])
    @equipment = Equipment.new
    @requests = current_user.equipment.where(request: true)
    @send_requests = current_user.send_requests
    @receive_requests = current_user.receive_requests
  end

  def index
    @lab_owners = LabOwner.all
  end
end

app/controllers/move_requests_controller.rb
class MoveRequestsController < ApplicationController
  before_action :authenticate_user!

  def create
    @move_request = current_user.send_requests.build(move_request_params)
    @equipment = @move_request.equipment
    @equipment.update_attributes(in_transit: true)
    if @move_request.save
      @equipment.save
      flash[:success] = "Move request created successfully!"
      redirect_to user_dashboard
    else
      flash[:danger] = "Move request could not be added!"
      redirect_to user_dashboard
    end
  end

  def update
    @move_request = MoveRequest.find(params[:id])
    @move_request.update_attributes(move_request_params)
    @move_request.save
    @move_request.move_equipment
    @move_request.equipment.update_location_history
    redirect_to user_dashboard
  end


  private
    def move_request_params
      params.require(:move_request).permit(:to_id, :equipment_id, :hod_approved, :to_approved)
    end

    def user_dashboard
      if current_user.nil?
        root_path
      elsif current_user.type == 'StoreManager'
        store_manager_path(current_user)
      elsif current_user.type == 'LabOwner'
        lab_owner_path(current_user)
      elsif current_user.type == 'SuperUser'
        super_user_path(current_user)
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/super_users_controller.rb
class SuperUsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @store_manager = SuperUser.find(params[:id])
    @requests = Equipment.where(request: true)
    @move_requests = MoveRequest.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(name="")
    base_title = "Equipment Tracker"
    if name.blank?
      title = base_title   
    else
      title = "#{name} | #{base_title}"
    end
  end

  def is_super_user?
    user_signed_in? && current_user.type == 'SuperUser'
  end

  def is_store_manager?
    user_signed_in? && current_user.type == 'StoreManager'
  end

  def is_lab_owner?
    user_signed_in? && current_user.type == 'LabOwner'
  end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/move_requests_helper.rb
module MoveRequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Equipment Tracker", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if user_signed_in? && current_user.type == 'LabOwner' %>
              <li>
                <%= link_to('All Equipment', equipment_index_path) %>
              </li>
              <li>
                <%= link_to 'Labs', lab_owners_path %>
              </li>
              <li>
                <%= link_to('Dashboard', lab_owner_path(current_user)) %>  
              </li>
              <li>
                <%= link_to('Logout', destroy_lab_owner_session_path, :method => :delete) %>  
              </li>
            <% elsif user_signed_in? && current_user.type == 'StoreManager' %>
              <li>
                <%= link_to('All Equipment', equipment_index_path) %>
              </li>
              <li>
                <%= link_to 'Labs', lab_owners_path %>
              </li>
              <li>
                <%= link_to('Dashboard', store_manager_path(current_user)) %>  
              </li>
              <li>
              <%= link_to('Logout', destroy_store_manager_session_path, :method => :delete) %>  
              </li>
            <% elsif user_signed_in? && current_user.type == 'SuperUser' %>
              <li>
                <%= link_to('Dashboard', super_user_path(current_user)) %>  
              </li>
              <li>
                <%= link_to 'Labs', lab_owners_path %>
              </li>
              <li>
              <%= link_to('Logout', destroy_super_user_session_path, :method => :delete) %>  
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path)  %>  
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>